"use client";

// Composer per spec 03 D2: account multi-select row, media strip + dropzone
// (click / drag / paste / Import), an AI caption brief, platform captions,
// Media Preview rail, Schedule card, and Update/Duplicate/Delete in edit mode.
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Icon } from "./icons";
import { AccountAvatar, PlatformIcon } from "./platform-icon";
import { InfoTip } from "./ui";
import { ActionButton } from "./interactive";
import { platform as platformOf, FOUR_IMAGE_PLATFORMS, type PostType } from "@/lib/platforms";
import { MediaLibraryModal, MediaThumb, uploadOneFile, type ComposerMedia } from "./media";
import { localDateInputValue, nextMinuteInputValue, isPastSchedule, isPastToday, scheduleMinDate, scheduleMinTime } from "@/lib/format";
import { CaptionBrief, CaptionEditor } from "./caption-editor";
import { CreatePostVideoVariant, VideoLibraryDestinationDialog } from "./create-post-video-variant";
import { VIDEO_PRESETS } from "@/lib/video-render-settings";

export type { ComposerMedia };

export type ComposerAccount = {
  id: number;
  platform: string;
  username: string;
  status: string;
  avatar_url: string | null;
};
export type ComposerPost = {
  id: string;
  caption: string;
  status: string;
  is_draft: boolean;
  scheduled_at: string | null;
  social_accounts: number[];
  platform_configurations: Record<string, Record<string, unknown>>;
};
export type ComposerStudioRender = {
  mediaId: string;
  platformId: string;
  aspectRatio: string;
};

const TYPE_LABEL: Record<PostType, string> = {
  text: "text post",
  image: "image post",
  video: "video post",
  story: "story post",
};

const ACCEPT: Record<PostType, string> = {
  text: "",
  image: "image/*,application/pdf",
  video: "video/*",
  story: "image/*,video/*",
};

const ACCEPT_LABEL: Record<PostType, string> = {
  text: "",
  image: "images or PDFs",
  video: "videos",
  story: "images or videos",
};

/** Drag-and-drop and paste bypass the file input's `accept` attribute, so this
 *  re-checks the same allowlist manually. */
function fileAllowed(file: File, accept: string): boolean {
  if (!accept) return true;
  return accept.split(",").some((pattern) => {
    pattern = pattern.trim();
    return pattern.endsWith("/*") ? file.type.startsWith(pattern.slice(0, -1)) : file.type === pattern;
  });
}

export function Composer({
  type,
  mode,
  accounts,
  pref24h,
  prefFilenameCaption,
  entitled,
  freeRemaining,
  post,
  initialMedia,
  initialDate,
  initialTime,
  initialSelectedAccountIds,
  initialPlatformCaptions,
  initialCaptionBrief,
  initialCaptionLength,
  initialStudioRenders,
}: {
  type: PostType;
  mode: "create" | "edit";
  accounts: ComposerAccount[];
  pref24h: boolean;
  prefFilenameCaption: boolean;
  entitled: boolean;
  freeRemaining: number;
  post: ComposerPost | null;
  initialMedia: ComposerMedia[];
  initialDate?: string;
  /** Paired with initialDate for a Content Studio hand-off that already has
   *  a publish time chosen; ignored without initialDate. */
  initialTime?: string;
  /** Preselects "Post to" when handed off from a finished Content Studio
   *  render (Publish, or the Library's "Create post") — not an edit, so
   *  separate from `post.social_accounts`. */
  initialSelectedAccountIds?: number[];
  /** Platform-level captions generated by Content Studio. */
  initialPlatformCaptions?: Record<string, string>;
  /** AI prompt and length selected in Content Studio. */
  initialCaptionBrief?: string;
  initialCaptionLength?: "short" | "medium" | "long";
  /** Exact platform-specific exports from a Content Studio hand-off. */
  initialStudioRenders?: ComposerStudioRender[];
}) {
  const router = useRouter();
  const eligible = useMemo(
    () => accounts.filter((a) => platformOf(a.platform)?.supports.includes(type)),
    [accounts, type]
  );

  const [selected, setSelected] = useState<Set<number>>(
    () => new Set(post?.social_accounts ?? initialSelectedAccountIds ?? [])
  );
  const [remember, setRemember] = useState(false);
  const [search, setSearch] = useState("");
  const [showSearch, setShowSearch] = useState(false);
  // Native `title` tooltips on the account avatars got clipped — the row
  // scrolls horizontally (overflow-x-auto), which per the CSS overflow spec
  // forces overflow-y to auto too, cutting off anything escaping the row's
  // own height. Fixed positioning (computed on hover, below the avatar)
  // sidesteps that clipping entirely.
  const [accountTooltip, setAccountTooltip] = useState<{ x: number; y: number; text: string } | null>(null);
  const [caption, setCaption] = useState(post?.caption ?? initialCaptionBrief ?? "");
  const [media, setMedia] = useState<ComposerMedia[]>(initialMedia);
  const [uploading, setUploading] = useState(0);
  const [previewIdx, setPreviewIdx] = useState(0);
  const [videoVariants, setVideoVariants] = useState<ComposerStudioRender[]>([]);
  const [configs, setConfigs] = useState<Record<string, Record<string, unknown>>>(() =>
    post?.platform_configurations
      ?? Object.fromEntries(Object.entries(initialPlatformCaptions ?? {}).map(([platformId, platformCaption]) => [platformId, { caption: platformCaption }]))
  );
  const [captionLength, setCaptionLength] = useState<"short" | "medium" | "long">(initialCaptionLength ?? "medium");
  const initialSchedule = post?.scheduled_at ? new Date(post.scheduled_at) : null;
  const [scheduleOn, setScheduleOn] = useState(!!initialSchedule || !!initialDate);
  const [date, setDate] = useState(
    initialSchedule ? toDateInput(initialSchedule) : (initialDate ?? "")
  );
  const [time, setTime] = useState(
    initialSchedule ? toTimeInput(initialSchedule) : initialDate ? (initialTime ?? "12:00") : ""
  );
  const earliestDate = localDateInputValue();
  const earliestTime = nextMinuteInputValue();
  const scheduleIsPast = scheduleOn && isPastSchedule(date, time);
  const scheduleIsPastToday = scheduleOn && isPastToday(date, time);
  function updateDate(value: string) {
    if (!value || value < earliestDate) return;
    setDate(value);
    if (value === earliestDate && time < earliestTime) setTime(earliestTime);
  }
  function updateTime(value: string) {
    if (!value || (date === earliestDate && value < earliestTime)) return;
    setTime(value);
  }
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [libraryOpen, setLibraryOpen] = useState(false);
  const [libraryDestinationOpen, setLibraryDestinationOpen] = useState(false);
  const [libraryDestination, setLibraryDestination] = useState<{ id: number; platform: string } | null>(null);
  const [pendingRemoveId, setPendingRemoveId] = useState<string | null>(null);
  const fileInput = useRef<HTMLInputElement>(null);
  const studioRenders = useMemo(
    () => [...(initialStudioRenders ?? []), ...videoVariants].filter((render) => media.some((item) => item.id === render.mediaId)),
    [initialStudioRenders, media, videoVariants]
  );
  const libraryAspectRatios = useMemo(() => {
    if (!libraryDestination) return undefined;
    return [...new Set(VIDEO_PRESETS.filter((preset) => preset.targets.some((target) => target.platformId === libraryDestination.platform)).map((preset) => preset.aspect.id))];
  }, [libraryDestination]);

  function addOrReplaceVideoVariant(variantMedia: ComposerMedia, platformId: string, aspectRatio: string, accountId: number) {
    const mediaToRemove = new Set(studioRenders.filter((render) => render.platformId === platformId).map((render) => render.mediaId));
    setMedia((current) => [...current.filter((item) => !mediaToRemove.has(item.id) && item.id !== variantMedia.id), variantMedia]);
    setVideoVariants((current) => [...current.filter((render) => render.platformId !== platformId), { mediaId: variantMedia.id, platformId, aspectRatio }]);
    setSelected((current) => new Set([...current, accountId]));
  }

  const rememberKey = `pt_remember_accounts_${type}`;
  useEffect(() => {
    // A Content Studio hand-off already picked the destinations — a stale
    // "Remember" set from an unrelated post shouldn't override that.
    if (mode !== "create" || (initialSelectedAccountIds && initialSelectedAccountIds.length > 0)) return;
    try {
      const saved = localStorage.getItem(rememberKey);
      if (saved) {
        const ids = JSON.parse(saved) as number[];
        setSelected(new Set(ids.filter((id) => eligible.some((a) => a.id === id))));
        setRemember(true);
      }
    } catch {}
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    if (!remember) {
      localStorage.removeItem(rememberKey);
    } else {
      localStorage.setItem(rememberKey, JSON.stringify([...selected]));
    }
  }, [remember, selected, rememberKey]);

  const selectedPlatforms = useMemo(() => {
    const set = new Set<string>();
    for (const a of eligible) if (selected.has(a.id)) set.add(a.platform);
    return set;
  }, [selected, eligible]);

  const filteredAccounts = eligible.filter(
    (a) =>
      !search ||
      a.username.toLowerCase().includes(search.toLowerCase()) ||
      a.platform.includes(search.toLowerCase())
  );

  function setPlatformCaption(platformId: string, value: string) {
    setConfigs((current) => ({
      ...current,
      [platformId]: { ...(current[platformId] ?? {}), caption: value },
    }));
  }

  async function uploadFiles(files: FileList | File[]) {
    const accept = ACCEPT[type];
    const list = Array.from(files).filter((file) => fileAllowed(file, accept));
    if (list.length < files.length) {
      setError(`Only ${ACCEPT_LABEL[type]} can be added to a ${TYPE_LABEL[type]}.`);
    }
    for (const file of list) {
      setUploading((u) => u + 1);
      try {
        const uploaded = await uploadOneFile(file);
        setMedia((m) => [...m, uploaded]);
        if (prefFilenameCaption && !caption) {
          setCaption(file.name.replace(/\.[^.]+$/, ""));
        }
      } catch (e) {
        setError(e instanceof Error ? e.message : "Upload failed");
      } finally {
        setUploading((u) => u - 1);
      }
    }
  }

  function buildPayload(extra: Record<string, unknown>) {
    const platformConfigs: Record<string, Record<string, unknown>> = {};
    for (const p of selectedPlatforms) {
      const merged = { ...(configs[p] ?? {}) };
      const variant = studioRenders.find((render) => render.platformId === p);
      if (variant) {
        merged.video_variant_media_id = variant.mediaId;
        merged.video_variant_aspect_ratio = variant.aspectRatio;
      }
      const clean = Object.fromEntries(
        Object.entries(merged).filter(([, v]) => v !== "" && v !== undefined && v !== null && v !== false)
      );
      if (Object.keys(clean).length) platformConfigs[p] = clean;
    }
    const accountConfigurations = [...selected].flatMap((accountId) => {
      const account = eligible.find((item) => item.id === accountId);
      const platformCaption = account ? (configs[account.platform]?.caption as string | undefined) : undefined;
      return platformCaption?.trim() ? [{ account_id: accountId, caption: platformCaption.trim() }] : [];
    });
    return {
      type,
      caption,
      media: media.map((m) => m.id),
      social_accounts: [...selected],
      platform_configurations: platformConfigs,
      account_configurations: accountConfigurations,
      ...extra,
    };
  }

  function scheduledIso(): string | null {
    if (!date || !time) return null;
    const d = new Date(`${date}T${time}`);
    return isNaN(d.getTime()) ? null : d.toISOString();
  }

  async function submit(extra: Record<string, unknown>, successPath: string) {
    setBusy(true);
    setError(null);
    try {
      const isEdit = mode === "edit";
      const res = await fetch(isEdit ? `/api/app/posts/${post!.id}` : "/api/app/posts", {
        method: isEdit ? "PATCH" : "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(buildPayload(extra)),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) {
        setError(data?.error?.message ?? "Something went wrong.");
        return;
      }
      router.push(successPath);
      router.refresh();
    } finally {
      setBusy(false);
    }
  }

  const editable = mode === "create" || ["draft", "scheduled"].includes(post?.status ?? "");
  const missingCaptions = type === "text"
    ? [...selectedPlatforms].filter((p) => !((configs[p]?.caption as string) ?? "").trim())
    : [];
  const hasMissingCaptions = missingCaptions.length > 0;
  const updateWillPublish = scheduleOn && !!scheduledIso();
  const showFourImageWarning =
    media.filter((m) => m.kind !== "video").length > 4 &&
    FOUR_IMAGE_PLATFORMS.some((p) => selectedPlatforms.has(p));

  const timeCaption = (() => {
    const iso = scheduledIso();
    if (!iso) return null;
    const d = new Date(iso);
    const t = d.toLocaleTimeString([], {
      hour: pref24h ? "2-digit" : "numeric",
      minute: "2-digit",
      hour12: !pref24h,
    });
    return `Your post will be posted at ${t} in your local time.`;
  })();

  return (
    <div className="fade-up grid gap-6 lg:grid-cols-[1fr_320px]">
      {/* ── Main column ─────────────────────────────────────── */}
      <div className="min-w-0">
        <h1 className="text-2xl font-bold">
          {mode === "edit" ? `Edit your ${TYPE_LABEL[type]}` : `Create ${TYPE_LABEL[type]}`}
        </h1>
        {/* Account selector */}
        <div className="mt-5 flex items-center justify-between">
          <button
            type="button"
            className="flex items-center gap-1 text-sm font-semibold text-muted hover:text-ink"
            onClick={() => setShowSearch((v) => !v)}
          >
            Search &amp; Filter <Icon name="chevronDown" size={14} />
          </button>
          <label className="flex items-center gap-2 text-xs font-semibold text-muted">
            Remember
            <button
              type="button"
              role="switch"
              aria-checked={remember}
              className="pt-toggle scale-90"
              data-on={remember}
              onClick={() => setRemember((v) => !v)}
            >
              <span />
            </button>
          </label>
        </div>
        {showSearch && (
          <input
            className="input mt-2"
            placeholder="Filter accounts by handle or platform…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        )}
        <div className="mt-3 flex gap-3 overflow-x-auto px-2 py-3">
          {filteredAccounts.length === 0 && (
            <p className="text-sm text-muted">
              No {type}-capable accounts connected yet — add some under Connections.
            </p>
          )}
          {filteredAccounts.map((a) => (
            <div key={a.id} className="flex shrink-0 flex-col items-center gap-1">
              <button
                type="button"
                aria-label={`@${a.username} · ${platformOf(a.platform)?.name}${a.status !== "active" ? " (needs re-auth)" : ""}`}
                onMouseEnter={(e) => {
                  const rect = e.currentTarget.getBoundingClientRect();
                  setAccountTooltip({
                    x: rect.left + rect.width / 2,
                    y: rect.bottom + 6,
                    text: `@${a.username} · ${platformOf(a.platform)?.name}${a.status !== "active" ? " (needs re-auth)" : ""}`,
                  });
                }}
                onMouseLeave={() => setAccountTooltip(null)}
                onClick={() =>
                  setSelected((s) => {
                    const next = new Set(s);
                    if (next.has(a.id)) next.delete(a.id);
                    else next.add(a.id);
                    return next;
                  })
                }
                disabled={!editable}
              >
                <AccountAvatar
                  username={a.username}
                  platformId={a.platform}
                  avatarUrl={a.avatar_url}
                  size={44}
                  selected={selected.has(a.id)}
                />
              </button>
              {a.platform === "tiktok" && selected.has(a.id) && (
                <span className="text-[10px] font-semibold text-muted" title="Uploads to your TikTok inbox as a draft">
                  Draft
                </span>
              )}
            </div>
          ))}
        </div>
        {accountTooltip && (
          <span
            className="pointer-events-none fixed z-50 -translate-x-1/2 whitespace-nowrap rounded-md bg-ink px-2 py-1 text-xs font-semibold text-white shadow-lg"
            style={{ left: accountTooltip.x, top: accountTooltip.y }}
          >
            {accountTooltip.text}
          </span>
        )}

        {/* Media */}
        {type !== "text" && (
          <div className="mt-4">
            {media.length > 0 && (
              <div className="mb-4 flex gap-3 overflow-x-auto px-2.5 pb-1 pt-3">
                {media.map((m, i) => {
                  const studioRender = studioRenders.find((render) => render.mediaId === m.id);
                  const platformName = studioRender ? platformOf(studioRender.platformId)?.name ?? studioRender.platformId : null;
                  return (
                  <div key={m.id} className="group relative shrink-0">
                    <div className="overflow-hidden rounded-xl shadow-[0_1px_2px_rgba(6,63,59,0.08)] ring-1 ring-line transition-shadow group-hover:ring-primary/50">
                      <MediaThumb media={m} size={128} onClick={() => setPreviewIdx(i)} />
                    </div>
                    {studioRender && (
                      <span
                        className="absolute bottom-1.5 left-1.5 inline-flex h-6 w-6 items-center justify-center rounded-full bg-white shadow-sm ring-1 ring-line"
                        title={`Rendered for ${platformName}`}
                        aria-label={`Rendered for ${platformName}`}
                      >
                        <PlatformIcon id={studioRender.platformId} size={14} />
                      </span>
                    )}
                    {editable && (
                      <button
                        type="button"
                        aria-label={`Remove ${m.name}`}
                        className="absolute -right-2 -top-2 z-10 flex h-6 w-6 items-center justify-center rounded-full bg-ink text-white opacity-0 shadow-md ring-2 ring-white transition-opacity hover:bg-black group-hover:opacity-100 focus-visible:opacity-100"
                        onClick={() => setPendingRemoveId(m.id)}
                      >
                        <Icon name="x" size={12} strokeWidth={2.5} />
                      </button>
                    )}
                  </div>
                  );
                })}
              </div>
            )}
            {editable && (
              <div
                className="flex cursor-pointer flex-col items-center gap-1.5 rounded-2xl border-2 border-dashed border-line bg-white p-6 text-center transition-colors hover:border-primary"
                onClick={() => type !== "video" && fileInput.current?.click()}
                onDragOver={(e) => e.preventDefault()}
                onDrop={(e) => {
                  e.preventDefault();
                  uploadFiles(e.dataTransfer.files);
                }}
                onPaste={(e) => {
                  if (e.clipboardData.files.length) uploadFiles(e.clipboardData.files);
                }}
                tabIndex={0}
                role="button"
                aria-label="Upload media"
              >
                <Icon name="upload" size={22} className="text-muted" />
                <p className="text-sm font-semibold">
                  Click to upload or drag and drop
                </p>
                <p className="text-xs text-muted">
                  …or hover and paste from your clipboard —{" "}
                  {type === "video"
                    ? "Video"
                    : type === "story"
                      ? "Image or video"
                      : "Image(s) or PDF"}
                  {/* The PDF caveat is genuinely non-obvious and earns a tip;
                      the size limit is plain text, since an icon you have to
                      hover to learn a number reads as broken. */}
                  {type === "image" ? (
                    <>
                      {" "}
                      <InfoTip text="PDFs are attached as a document in this build; production rasterizes each page to an image." />
                    </>
                  ) : (
                    " · Max 250MB per file"
                  )}
                </p>
                <div className="mt-2 flex flex-wrap justify-center gap-2">
                  {type === "video" ? (
                    <CreatePostVideoVariant
                      accounts={eligible}
                      usedPlatforms={studioRenders.map((render) => render.platformId)}
                      onComplete={({ media: variantMedia, platformId, aspectRatio, accountId }) => {
                        addOrReplaceVideoVariant(variantMedia, platformId, aspectRatio, accountId);
                      }}
                    />
                  ) : (
                    <button
                      type="button"
                      className="btn-primary !py-1.5"
                      onClick={(e) => {
                        e.stopPropagation();
                        fileInput.current?.click();
                      }}
                    >
                      <Icon name="upload" size={16} /> Upload media
                    </button>
                  )}
                  <button
                    type="button"
                    className="btn-subtle !py-1.5"
                    onClick={(e) => {
                      e.stopPropagation();
                      if (type === "video") setLibraryDestinationOpen(true);
                      else setLibraryOpen(true);
                    }}
                  >
                    <Icon name="image" size={16} />
                    Library
                  </button>
                </div>
              </div>
            )}
            <input
              ref={fileInput}
              type="file"
              hidden
              multiple={type !== "video"}
              accept={ACCEPT[type]}
              onChange={(e) => {
                if (e.target.files) uploadFiles(e.target.files);
                e.target.value = "";
              }}
            />
          </div>
        )}

        {/* AI brief + platform captions */}
        <div className="mt-6 border-t border-line pt-5">
          <CaptionBrief
            value={caption}
            onChange={setCaption}
            length={captionLength}
            onLengthChange={setCaptionLength}
            disabled={!editable}
            onPaste={(event) => {
              if (event.clipboardData.files.length && type !== "text") {
                event.preventDefault();
                uploadFiles(event.clipboardData.files);
              }
            }}
          />

          <div className="mt-6">
            <p className="text-xs font-bold uppercase tracking-[0.1em] text-muted">Platform captions{type !== "text" && " (optional)"}</p>
            {selectedPlatforms.size === 0 ? (
              <p className="mt-2 rounded-xl border border-dashed border-line px-4 py-5 text-sm text-muted">Select at least one account under Post to, then AI can tailor the caption for each platform.</p>
            ) : (
              <div className="mt-3 flex flex-col gap-4">
                {[...selectedPlatforms].map((platformId) => (
                  <CaptionEditor
                    key={platformId}
                    platformId={platformId}
                    value={(configs[platformId]?.caption as string) ?? ""}
                    onChange={(next) => setPlatformCaption(platformId, next)}
                    brief={caption}
                    length={captionLength}
                    format={type === "video" ? "video" : "post"}
                    disabled={!editable}
                    required={type === "text"}
                  />
                ))}
              </div>
            )}
          </div>
          {uploading > 0 && (
            <p className="mt-3 flex items-center gap-2 text-sm font-semibold text-primary-deep">
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
              Sending to server… don&apos;t close this window while media uploads.
            </p>
          )}
        </div>

        {error && <p className="mt-4 text-sm font-semibold text-danger">{error}</p>}
      </div>

      {/* ── Right rail ──────────────────────────────────────── */}
      <div className="flex flex-col gap-4 self-start lg:sticky lg:top-20">
        {type !== "text" && (
          <div className="card p-4">
            <p className="text-sm font-bold">Media Preview</p>
            {showFourImageWarning && (
              <p className="mt-2 rounded-lg bg-warning-bg p-2.5 text-xs font-medium text-warning-ink">
                Heads up: only the first 4 images will post to Twitter/X, Bluesky and
                Threads.
              </p>
            )}
            {media.length === 0 ? (
              <p className="mt-3 py-8 text-center text-sm text-muted">Nothing attached yet</p>
            ) : (
              <div className="mt-3">
                {studioRenders.length > 0 && (
                  <div className="mb-3 flex flex-wrap gap-2" aria-label="Studio render formats">
                    {studioRenders.map((render) => {
                      const index = media.findIndex((item) => item.id === render.mediaId);
                      const selectedRender = index === previewIdx;
                      return (
                        <button
                          key={render.mediaId}
                          type="button"
                          onClick={() => setPreviewIdx(index)}
                          aria-pressed={selectedRender}
                          aria-label={`${platformOf(render.platformId)?.name ?? render.platformId}, ${render.aspectRatio}`}
                          className={`inline-flex min-h-9 items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-xs font-bold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${selectedRender ? "border-primary bg-primary/10 text-primary-deep" : "border-line bg-page text-muted hover:border-primary/60 hover:text-ink"}`}
                        >
                          <PlatformIcon id={render.platformId} size={15} />
                          <span>{render.aspectRatio}</span>
                        </button>
                      );
                    })}
                  </div>
                )}
                <div className="relative">
                  <MediaThumb
                    media={media[Math.min(previewIdx, media.length - 1)]}
                    size={280}
                    full
                    aspectRatio={studioRenders.find((render) => render.mediaId === media[Math.min(previewIdx, media.length - 1)]?.id)?.aspectRatio}
                  />
                  {media.length > 1 && (
                    <>
                      <button
                        type="button"
                        aria-label="Previous"
                        className="absolute left-1.5 top-1/2 -translate-y-1/2 rounded-full bg-white/90 p-1 shadow"
                        onClick={() => setPreviewIdx((i) => (i - 1 + media.length) % media.length)}
                      >
                        <Icon name="chevronLeft" size={16} />
                      </button>
                      <button
                        type="button"
                        aria-label="Next"
                        className="absolute right-1.5 top-1/2 -translate-y-1/2 rounded-full bg-white/90 p-1 shadow"
                        onClick={() => setPreviewIdx((i) => (i + 1) % media.length)}
                      >
                        <Icon name="chevronRight" size={16} />
                      </button>
                    </>
                  )}
                </div>
                {media.length > 1 && (
                  <div className="mt-2 flex justify-center gap-1.5">
                    {media.map((_, i) => (
                      <button
                        key={i}
                        type="button"
                        aria-label={`Preview ${i + 1}`}
                        className={`h-1.5 w-1.5 rounded-full ${i === previewIdx ? "bg-primary-deep" : "bg-line"}`}
                        onClick={() => setPreviewIdx(i)}
                      />
                    ))}
                  </div>
                )}
                <p className="mt-2 truncate text-center text-xs text-muted">
                  {media[Math.min(previewIdx, media.length - 1)]?.name}
                </p>
              </div>
            )}
          </div>
        )}

        <div className="card p-4">
          <div className="flex items-center justify-between">
            <p className="text-sm font-bold">Schedule post</p>
            <button
              type="button"
              role="switch"
              aria-checked={scheduleOn}
              className="pt-toggle"
              data-on={scheduleOn}
              onClick={() => setScheduleOn((v) => !v)}
              disabled={!editable}
            >
              <span />
            </button>
          </div>
          {scheduleOn && (
            <div className="mt-3 flex flex-col gap-2">
              <div className="flex gap-2">
                <input
                  type="date"
                  className="input"
                  min={scheduleMinDate(date, earliestDate)}
                  value={date}
                  onChange={(e) => updateDate(e.target.value)}
                />
                <input
                  type="time"
                  className="input"
                  min={scheduleMinTime(date, time, earliestDate, earliestTime)}
                  value={time}
                  onChange={(e) => updateTime(e.target.value)}
                />
              </div>
              {scheduleIsPastToday ? (
                <p className="flex items-center gap-1.5 text-xs font-semibold text-amber-700" role="alert">
                  <Icon name="warningTriangle" size={14} /> This time has already passed today. Your post will go live immediately.
                </p>
              ) : scheduleIsPast ? (
                <p className="flex items-center gap-1.5 text-xs font-semibold text-red-700" role="alert">
                  <Icon name="warningTriangle" size={14} /> Can't schedule posts in the past.
                </p>
              ) : (
                timeCaption && <p className="text-xs text-muted">{timeCaption}</p>
              )}
            </div>
          )}

          <div className="mt-4 flex flex-col gap-2">
            {mode === "create" ? (
              <>
                {scheduleOn ? (
                  <button
                    className="btn-composer-primary w-full"
                    disabled={busy || selected.size === 0 || !scheduledIso() || uploading > 0 || (scheduleIsPast && !scheduleIsPastToday) || hasMissingCaptions}
                    onClick={() =>
                      submit({ scheduled_at: scheduledIso() }, "/dashboard/posts?status=scheduled")
                    }
                  >
                    {scheduleIsPast && !scheduleIsPastToday ? <><Icon name="warningTriangle" size={15} /> Update schedule</> : "Schedule"}
                  </button>
                ) : (
                  <button
                    className="btn-composer-primary w-full"
                    disabled={busy || selected.size === 0 || uploading > 0 || hasMissingCaptions}
                    onClick={() => submit({}, "/dashboard/posts")}
                  >
                    Post now
                  </button>
                )}
                <button
                  className="btn-subtle w-full"
                  disabled={busy || selected.size === 0 || uploading > 0 || hasMissingCaptions}
                  onClick={() => submit({ use_queue: true }, "/dashboard/posts?status=scheduled")}
                  title="Assign the next free queue slot from Settings → Queue"
                >
                  <Icon name="clock" size={15} /> Add to queue
                </button>
                <Link
                  href="/dashboard/settings/queue"
                  className="-mt-0.5 text-center text-xs font-semibold text-primary-deep underline-offset-2 hover:underline"
                >
                  Manage queue settings
                </Link>
                <button
                  className="btn-subtle w-full"
                  disabled={busy || selected.size === 0 || uploading > 0}
                  onClick={() => submit({ is_draft: true }, "/dashboard/posts?status=draft")}
                >
                  Save to Drafts
                </button>
              </>
            ) : editable ? (
              <>
                <button
                  className="btn-composer-primary w-full"
                  disabled={busy || selected.size === 0 || uploading > 0 || (scheduleOn && scheduleIsPast && !scheduleIsPastToday) || (updateWillPublish && hasMissingCaptions)}
                  onClick={() =>
                    submit(
                      scheduleOn && scheduledIso()
                        ? { scheduled_at: scheduledIso(), is_draft: false }
                        : { scheduled_at: null, is_draft: true },
                      scheduleOn ? "/dashboard/posts?status=scheduled" : "/dashboard/posts?status=draft"
                    )
                  }
                >
                  {scheduleOn && scheduleIsPast && !scheduleIsPastToday ? <><Icon name="warningTriangle" size={15} /> Update schedule</> : "Update"}
                </button>
                <DuplicateButton postId={post!.id} />
                <ActionButton
                  endpoint={`/api/app/posts/${post!.id}`}
                  method="DELETE"
                  confirmText="Delete this post? This cannot be undone."
                  redirectTo="/dashboard/posts"
                  className="btn-danger-soft w-full"
                  disabled={busy}
                >
                  Delete
                </ActionButton>
              </>
            ) : (
              <div className="flex flex-col gap-2">
                <p className="text-sm text-muted">
                  This post is {post?.status} — published posts can&apos;t be edited or
                  deleted.
                </p>
                <DuplicateButton postId={post!.id} />
              </div>
            )}
          </div>
        </div>
      </div>

      {libraryOpen && (
        <MediaLibraryModal
          onClose={() => {
            setLibraryOpen(false);
            setLibraryDestination(null);
          }}
          onPick={(m) => {
            if (type === "video" && libraryDestination && m.studio_aspect_ratio) {
              addOrReplaceVideoVariant(m, libraryDestination.platform, m.studio_aspect_ratio, libraryDestination.id);
            } else {
              setMedia((list) => (list.some((x) => x.id === m.id) ? list : [...list, m]));
            }
            setLibraryOpen(false);
            setLibraryDestination(null);
          }}
          kind={type === "video" ? "video" : type === "image" ? "image" : undefined}
          allowedAspectRatios={libraryAspectRatios}
        />
      )}

      {libraryDestinationOpen && (
        <VideoLibraryDestinationDialog
          accounts={eligible}
          usedPlatforms={studioRenders.map((render) => render.platformId)}
          onClose={() => setLibraryDestinationOpen(false)}
          onSelect={(account) => {
            setLibraryDestination(account);
            setLibraryDestinationOpen(false);
            setLibraryOpen(true);
          }}
        />
      )}

      {pendingRemoveId && (
        <div
          className="fixed inset-0 z-[70] flex items-center justify-center bg-black/30 p-4"
          onClick={() => setPendingRemoveId(null)}
        >
          <div className="card w-full max-w-sm p-5" onClick={(e) => e.stopPropagation()}>
            <p className="text-lg font-extrabold">Remove this media?</p>
            <p className="mt-2 text-sm text-muted">
              It&apos;ll be taken off this post. The file stays in your library.
            </p>
            <div className="mt-5 flex justify-end gap-2">
              <button type="button" className="btn-subtle" onClick={() => setPendingRemoveId(null)}>
                Cancel
              </button>
              <button
                type="button"
                className="btn-danger"
                onClick={() => {
                  setMedia((list) => list.filter((x) => x.id !== pendingRemoveId));
                  setPreviewIdx(0);
                  setPendingRemoveId(null);
                }}
              >
                Remove
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function DuplicateButton({ postId }: { postId: string }) {
  const router = useRouter();
  return (
    <button
      className="btn-composer-secondary w-full"
      onClick={async () => {
        const res = await fetch(`/api/app/posts/${postId}/duplicate`, { method: "POST" });
        const data = await res.json().catch(() => null);
        if (res.ok && data?.id) {
          router.push(`/dashboard/create/${data.id}`);
          router.refresh();
        }
      }}
    >
      Duplicate
    </button>
  );
}

function toDateInput(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function toTimeInput(d: Date): string {
  return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}
